### ISSUE TITLE
STA9750 fatima8808 MiniProject #00

### ISSUE THREAD

**Issue by fatima8808** [fatima8808/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://fatima8808.github.io/STA9750-2024-FALL

Thanks!
Fatima Wong

**Comment by michaelweylandt** [comment]
Thanks @fatima8808 !

Peer Feedback:

- @Dani-0000
- @Haina0
- @ElissaLeung

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @fatima8808.

Website URL should be: https://fatima8808.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @fatima8808 and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by ElissaLeung** [comment]
Hi @fatima8808 ! I liked reading your personal introduction on your website. Maybe you can add some links to your introduction and/or some visuals (e.g. professional headshot). Hopefully, after this semester, you can also include a portfolio of our data analytics projects from this class! Otherwise, I liked your website.

**Comment by Dani-0000** [comment]
Hey @fatima8808, I enjoyed the title of your introduction and bio. As we progress in this course, I believe your website will look fantastic with links and various font styles.

**Comment by Haina0** [comment]
Hi @fatima8808 great job getting your website running, I enjoyed reading your introductory bio and look forward to see what you add to it throughout the course.
